### PR TITLE
subconverter: bump source and related dependencies

### PR DESCRIPTION
**Pull request by 1715173329**
Signed-off-by: CN_SZTL <cnsztl@project-openwrt.eu.org>

### CODE REVIEW

**Comment by tindy2013** [comment]
@1715173329 隔壁好心的 OpenWRT 分支的开发者帮咱修好了 Makefile

**Comment by NevadaCities** [comment]
@tindy2013 直接回复了

**Comment by tindy2013** [comment]
Thanks for this PR.

**Comment by 1715173329** [comment]
My pleasure.

**Pull request merged**
